# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bAOICq_wgmNqw5kpUOKvdKP1Vd4m3EzI
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

# ---------------------------------------------------
# PAGE CONFIG
# ---------------------------------------------------

st.set_page_config(
    page_title="Time Series Forecasting Dashboard",
    layout="wide"
)

# ---------------------------------------------------
# TITLE
# ---------------------------------------------------

st.title("📈 Time Series Forecasting & Portfolio Optimization Dashboard")

st.markdown("""
### Capstone Project 2026
ARIMA + LSTM Based NSE Stock Forecasting and Portfolio Optimization
""")

# ---------------------------------------------------
# SIDEBAR
# ---------------------------------------------------

st.sidebar.header("Dashboard Navigation")

section = st.sidebar.radio(
    "Go To",
    [
        "Overview",
        "Forecasting",
        "Portfolio Allocation",
        "Risk Analysis",
        "Execution Results"
    ]
)

# ---------------------------------------------------
# SAMPLE DATA
# ---------------------------------------------------

stocks = ['HDFC', 'INFY', 'RELIANCE', 'SUNPHARMA', 'ITC']

predicted_prices = [974.46, 1634.31, 1515.76, 1691.82, 397.74]

actual_prices = [981.20, 1648.10, 1502.90, 1704.55, 401.20]

allocation = [0, 32.22, 0, 0, 67.78]

volatility = [1.95, 1.21, 1.63, 1.17, 1.00]

returns = [-1.65, 0.78, -1.56, -1.01, 1.36]

portfolio_df = pd.DataFrame({
    "Stock": stocks,
    "Predicted Price": predicted_prices,
    "Actual Price": actual_prices,
    "Allocation (%)": allocation,
    "Volatility (%)": volatility,
    "Expected Return (%)": returns
})

# ---------------------------------------------------
# OVERVIEW PAGE
# ---------------------------------------------------

if section == "Overview":

    st.subheader("📊 Portfolio Overview")

    col1, col2, col3, col4 = st.columns(4)

    col1.metric("Total Capital", "₹10,00,000")
    col2.metric("Expected Return", "1.73%")
    col3.metric("Sharpe Ratio", "1.42")
    col4.metric("Best Model", "Tuned LSTM")

    st.dataframe(portfolio_df)

    fig = px.pie(
        portfolio_df,
        names='Stock',
        values='Allocation (%)',
        title='Portfolio Allocation'
    )

    st.plotly_chart(fig, use_container_width=True)

# ---------------------------------------------------
# FORECASTING PAGE
# ---------------------------------------------------

elif section == "Forecasting":

    st.subheader("📈 Forecasting Analysis")

    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=stocks,
        y=predicted_prices,
        mode='lines+markers',
        name='Predicted'
    ))

    fig.add_trace(go.Scatter(
        x=stocks,
        y=actual_prices,
        mode='lines+markers',
        name='Actual'
    ))

    fig.update_layout(
        title="Predicted vs Actual Prices",
        xaxis_title="Stocks",
        yaxis_title="Price"
    )

    st.plotly_chart(fig, use_container_width=True)

    st.markdown("### Model Evaluation")

    evaluation_df = pd.DataFrame({
        "Model": ["ARIMA", "Initial LSTM", "Tuned LSTM"],
        "RMSE": [10.23, 6.86, 4.08],
        "MAE": [8.71, 6.27, 3.24],
        "MAPE": ["N/A", "1.57", "0.81"],
        "Directional Accuracy": ["58%", "71%", "84%"]
    })

    st.dataframe(evaluation_df)

# ---------------------------------------------------
# PORTFOLIO PAGE
# ---------------------------------------------------

elif section == "Portfolio Allocation":

    st.subheader("💼 Portfolio Allocation")

    fig = px.bar(
        portfolio_df,
        x='Stock',
        y='Allocation (%)',
        color='Allocation (%)',
        title='Capital Allocation'
    )

    st.plotly_chart(fig, use_container_width=True)

    st.dataframe(portfolio_df)

# ---------------------------------------------------
# RISK ANALYSIS PAGE
# ---------------------------------------------------

elif section == "Risk Analysis":

    st.subheader("⚠️ Volatility & Risk Analysis")

    fig = px.bar(
        portfolio_df,
        x='Stock',
        y='Volatility (%)',
        color='Volatility (%)',
        title='Stock Volatility'
    )

    st.plotly_chart(fig, use_container_width=True)

    corr_data = np.array([
        [1.00, 0.72, 0.65, 0.40, 0.30],
        [0.72, 1.00, 0.58, 0.32, 0.25],
        [0.65, 0.58, 1.00, 0.44, 0.28],
        [0.40, 0.32, 0.44, 1.00, 0.22],
        [0.30, 0.25, 0.28, 0.22, 1.00]
    ])

    corr_df = pd.DataFrame(
        corr_data,
        columns=stocks,
        index=stocks
    )

    heatmap = px.imshow(
        corr_df,
        text_auto=True,
        title="Correlation Heatmap"
    )

    st.plotly_chart(heatmap, use_container_width=True)

# ---------------------------------------------------
# EXECUTION PAGE
# ---------------------------------------------------

elif section == "Execution Results":

    st.subheader("🚀 StockGro Execution Results")

    comparison_df = pd.DataFrame({
        "Stock": stocks,
        "Predicted Price": predicted_prices,
        "Actual Price": actual_prices
    })

    comparison_df["Error (%)"] = (
        abs(
            comparison_df["Actual Price"]
            - comparison_df["Predicted Price"]
        )
        /
        comparison_df["Actual Price"]
    ) * 100

    st.dataframe(comparison_df)

    st.success(
        "Portfolio generated positive returns with strong directional accuracy."
    )

    st.markdown("""
    ### Key Insights
    - Tuned LSTM outperformed ARIMA
    - Low forecast error achieved
    - Portfolio diversification reduced volatility
    - Directional predictions were highly accurate
    """)